<template>
  <div class="container">
    <div>{{cmsName}}分析页</div>
    <el-table
      :data="tableData"
      style="width: 100%">
      <el-table-column
        prop="date"
        label="日期"
        width="180">
      </el-table-column>
      <el-table-column
        prop="name"
        label="姓名"
        width="180">
      </el-table-column>
      <el-table-column
        prop="address"
        label="地址">
      </el-table-column>
    </el-table>

    <div class="echart-line">
      <echartsline :id="'fist'" v-if="msg.length" :echartsData="echartsData"></echartsline>
    </div>

    <div class="echart-line">
      <echartsline :id="'fist1'" v-if="msg.length" :echartsData="echartsData"></echartsline>
    </div>
   
  </div>
</template>

<script>
import echartsline from "@/components/echartsline";

export default {
  data () {
    return {
      tableData: [
        {
          date: '2016-05-02',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1518 弄'
        }, {
          date: '2016-05-04',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1517 弄'
        }, {
          date: '2016-05-01',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1519 弄'
        }, {
          date: '2016-05-03',
          name: '王小虎',
          address: '上海市普陀区金沙江路 1516 弄'
        }
      ],

      cmsName: this.$store.state.cmsName,

      mag: [],
      echartsData: null
    }
  
  },

  components: { echartsline },

  created() {
    this.initEchartsData();
  },

  methods: {
    initEchartsData() {
      this.msg = [
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-03-24 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":821,
          "monthSellMoney":1067.3,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":100,
          "sellMoney":130.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-03-25 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":895,
          "monthSellMoney":1163.5,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":94,
          "sellMoney":122.2,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-03-26 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":961,
          "monthSellMoney":1249.3,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":66,
          "sellMoney":85.8,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-03-27 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":948,
          "monthSellMoney":1232.4,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":59,
          "sellMoney":76.7,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-03-28 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":983,
          "monthSellMoney":1277.9,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":49,
          "sellMoney":63.7,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-03-29 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":1041,
          "monthSellMoney":1353.3,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":58,
          "sellMoney":75.4,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-03-30 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":1041,
          "monthSellMoney":1353.3,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-03-31 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":1007,
          "monthSellMoney":1309.1,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":30,
          "sellMoney":39.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"nike/耐克",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-01 00:00:00",
          "loc":"辽宁抚顺",
          "monthPrice":1.3,
          "monthSellAmount":915,
          "monthSellMoney":1189.5,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"品牌:Nike/耐克,鞋底是否有钉:有",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"耐克钉耐克塔钉7毫米耐克钉子鞋钉鞋鞋钉耐克碳钉每个",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-02 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":897,
          "monthSellMoney":1166.1,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-03 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":855,
          "monthSellMoney":1111.5,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-04 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":901,
          "monthSellMoney":1171.3,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":66,
          "sellMoney":85.8,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-05 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":901,
          "monthSellMoney":1171.3,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":14,
          "sellMoney":18.2,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-06 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":895,
          "monthSellMoney":1163.5,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":14,
          "sellMoney":18.2,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-07 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":883,
          "monthSellMoney":1147.9,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":4,
          "sellMoney":5.2,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-08 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":851,
          "monthSellMoney":1106.3,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-09 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":791,
          "monthSellMoney":1028.3,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-10 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":811,
          "monthSellMoney":1054.3,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":20,
          "sellMoney":26.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"nike/耐克",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-11 00:00:00",
          "loc":"辽宁抚顺",
          "monthPrice":1.3,
          "monthSellAmount":811,
          "monthSellMoney":1054.3,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"品牌:Nike/耐克,鞋底是否有钉:有",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"耐克钉耐克塔钉7毫米耐克钉子鞋钉鞋鞋钉耐克碳钉每个",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-12 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":825,
          "monthSellMoney":1072.5,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":14,
          "sellMoney":18.2,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-13 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":806,
          "monthSellMoney":1047.8,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":30,
          "sellMoney":39.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-14 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":776,
          "monthSellMoney":1008.8,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-15 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":756,
          "monthSellMoney":982.8,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-16 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":724,
          "monthSellMoney":941.2,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-17 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":722,
          "monthSellMoney":938.6,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":18,
          "sellMoney":23.4,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-18 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":708,
          "monthSellMoney":920.4,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-19 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":680,
          "monthSellMoney":884.0,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-20 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":680,
          "monthSellMoney":884.0,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"nike/耐克",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-21 00:00:00",
          "loc":"辽宁抚顺",
          "monthPrice":1.3,
          "monthSellAmount":636,
          "monthSellMoney":826.8,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"品牌:Nike/耐克,鞋底是否有钉:有",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"耐克钉耐克塔钉7毫米耐克钉子鞋钉鞋鞋钉耐克碳钉每个",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-22 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":636,
          "monthSellMoney":826.8,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        },
        {
          "brandName":"",
          "catName":"",
          "category":"50017271",
          "date":"2019-04-23 00:00:00",
          "loc":"",
          "monthPrice":1.3,
          "monthSellAmount":536,
          "monthSellMoney":696.8,
          "numberId":"524092439080",
          "picUrl":"",
          "price":1.3,
          "productUrl":"https://item.taobao.com/item.htm?id=524092439080",
          "propertyValue":"",
          "publishTime":"",
          "quantity":0,
          "sellAmount":0,
          "sellMoney":0.0,
          "shopName":"",
          "shopType":"C店",
          "shopUrl":"http://store.taobao.com/shop/view_shop.htm?user_number_id=56347267",
          "stopSale":false,
          "title":"",
          "uid":"56347267"
        }
      ];

      this.lineSellLineMOption(this.msg);
    
    },

    lineSellLineMOption(data) {

      let a = data;
      let msgname = ["销售额", "销售量"];
      let msgDate = [];

      let tsellMoney = []; //天猫
      let csellMoney = []; //淘宝

      for (let i in a) {
        let msgDate1 = a[i].date.split(" ")[0];
        let tsellMoney1 =
          this.radio == "a" ? a[i].sellMoney : a[i].monthSellMoney;
        let csellMoney1 =
          this.radio == "a" ? a[i].sellAmount : a[i].monthSellAmount;

        msgDate.push(msgDate1);
        tsellMoney.push(tsellMoney1);
        csellMoney.push(csellMoney1);
      }
      let series = [
        {
          name: "销售额",
          type: "line",
          data: tsellMoney
        },
        {
          name: "销售量",
          type: "line",
          data: csellMoney
        }
      ];
      let optionLine = {
        series: series,
        msgname: msgname,
        msgDate: msgDate
      };

      this.echartsData = optionLine;
    },
  }

}
</script>

<style lang="less" scoped>

.echart-line {
  height: 400px;
}

</style>
